//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Affilitest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AffilitestAccount
    {
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<bool> Active { get; set; }
        public System.Guid AffilitestAccountID { get; set; }
        public string CallsLeft { get; set; }
        public Nullable<int> Number { get; set; }
    }
}
