//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Affilitest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public System.Guid HistoryID { get; set; }
        public System.Guid UserID { get; set; }
        public string URL { get; set; }
        public string Date { get; set; }
        public string Click { get; set; }
        public string GEO { get; set; }
        public string Device { get; set; }
        public Nullable<System.DateTime> DateDefault { get; set; }
        public string Speed { get; set; }
        public string Status { get; set; }
    }
}
