//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Affilitest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SequenceUrl
    {
        public System.Guid SequenceID { get; set; }
        public string URL { get; set; }
        public string Device { get; set; }
        public string Country { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public System.DateTime Date { get; set; }
    }
}
